services:
  - type: web
    name: hotel-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node script.js
    envVars:
      - key: RENDER_USE_BUN
        value: "false"
      - key: NODE_VERSION
        value: "20"
